### ISSUE TITLE
巴哈的鏈接好像壞掉了哦

### ISSUE THREAD

**Issue by cpldhycxc** [jlhg/feedgen#1]
他現在只會提示items can't be fetched from the source URL: https://forum.gamer.com.tw/B.php?bsn=7650了欸

**Comment by cldotdev** [comment]
好像是 request 太頻繁被擋了，我換另台機器，暫時解決這問題，之後再觀察看看好了

**Comment by cpldhycxc** [comment]
感謝大大

**Comment by lchanc3** [comment]
從昨天下午3點開始，又發生巴哈連不上的狀況了
只有巴哈會這樣，感覺又是請求太頻繁（？

**Comment by cldotdev** [comment]
> 從昨天下午3點開始，又發生巴哈連不上的狀況了 只有巴哈會這樣，感覺又是請求太頻繁（？

看起來是主機被擋了跳需要手動驗證的網頁

**Comment by cldotdev** [comment]
暫時再換台主機，現在應該正常，找時間嘗試 selenium 的爬法 (#3)，看看能不能跳過驗證。

**Comment by lchanc3** [comment]
巴哈好像又改了新的擋爬蟲的方式，Feedgen 跟我自己弄的HTTP Request 爬小屋都不能用了。

**Comment by cldotdev** [comment]
這兩個 lib 可能有機會解網頁版的 Cloudflare anti-bot：

- https://pypi.org/project/cloudscraper/
- https://github.com/FlareSolverr/FlareSolverr

目前我打算用手機版的 request (https://api.gamer.com.tw/mobile_app/forum/v3/B.php?bsn=23805&order=post&page=1&type=1) 做成 feed。

**Comment by cldotdev** [comment]
已修復

**Comment by lchanc3** [comment]
> 巴哈好像又改了新的擋爬蟲的方式，Feedgen 跟我自己弄的HTTP Request 爬小屋都不能用了。

紀錄一下，發現小屋創作有手機版的API可以用 (https://api.gamer.com.tw/mobile_app/bahamut/v2/home_creation_detail.php?sn=5589584)
