### ISSUE TITLE
ptt 無法取得內容

### ISSUE THREAD

**Issue by lchanc3** [jlhg/feedgen#11]
批踢踢站方好像套了 Cloudflare 的防護

**Comment by cldotdev** [comment]
感謝回報，換了伺服器，現在應該正常了。

**Comment by lchanc3** [comment]
感謝修復
想問問是怎麼解決的，我有嘗試部屬一個來用，但是都會遇到這個問題，這種情況是需要換一個IP嗎？

**Comment by cldotdev** [comment]
原本是OVH IP 發現有擋，因此我換到 Hetzner Cloud，目前沒事，還要再觀察。
