### ISSUE TITLE
巴哈站規更改導致無法取得場外休憩區的資料

### ISSUE THREAD

**Issue by lchanc3** [jlhg/feedgen#5]
剛剛巴哈更改了站規(https://forum.gamer.com.tw/C.php?bsn=60096&snA=13272)

這導致場外版變成了隱版，API也需要登入才能取得資料
雖然不太看場外，但還是好奇有沒有什麼解法

**Comment by cldotdev** [comment]
如果站方有確實做好檢查登入的話，應該是沒辦法單純透過傳參數之類的手法繞過，還是得準備一組認證帳密來協助取得資料了。
