### ISSUE TITLE
遊戲角落無法取得摘要

### ISSUE THREAD

**Issue by lchanc3** [jlhg/feedgen#9]
網址 https://game.udn.com/rank/ajax_newest/2003/0/1 會有重定向次數過多的問題

測試發現把子域名改掉或移除就可以了
自己試下來 stars 和 500times 都可以(雖然不知道為什麼)
不過這樣改有點像是在跟 UDN 鬥法，不知道有沒有其他解法

**Comment by lchanc3** [comment]
另外，雖然和這件事沒有關係
~~想問一下為什麼 Feedbro 無法抓取批踢踢實業坊的摘要~~ 這個應該問Feedbro作者才對，抱歉
還有為什麼批踢踢實業坊的摘要時間順序是反過來的(?)

使用的瀏覽器是 Firefox 123，Feedbro 版本 4.15.10
謝謝

**Comment by cldotdev** [comment]
> 網址 https://game.udn.com/rank/ajax_newest/2003/0/1 會有重定向次數過多的問題
> 
> 測試發現把子域名改掉或移除就可以了 自己試下來 stars 和 500times 都可以(雖然不知道為什麼) 不過這樣改有點像是在跟 UDN 鬥法，不知道有沒有其他解法

猜是 API 有變，有試著用 `curl 'https://game.udn.com/rank/newest/2003'` 發現另一個資料來源網址，而且是同個子網域：https://game.udn.com/game/load/article/newest/?limit=20&time=&fl=author,view,photo,cate,hash

另一個是 https://game.udn.com/game/load/article/trend/?limit=20&time=7in30&fl=author,view,photo,cate,hash

我改用這個來源試試。

> 為什麼 Feedbro 無法抓取批踢踢實業坊的摘要

至於 Feedbro 無法顯示的問題，經過修改 updated 測試發現，2024-03-08T08:11:37Z 可以顯示 (顯示 4x 分鐘前)，但改成 2024-03-08T16:11:37Z 就無法顯示 (測試時間是台灣時間下午4點多)。猜是因為 feed 的時區是 UTC+08:00，但 Feedbro 是 UTC+00:00，所以在轉換「 多久時間以前」的文字時出現問題。我再研究一下是否可以在 feed 加入時區資訊，或乾脆統一用 UTC+00:00。

> 還有為什麼批踢踢實業坊的摘要時間順序是反過來的(?)

feed 內的 entry 並未嚴格按照 updated 的時間排序，理論上 RSS 客戶端應該會處理。我是用 tt-rss，PTT 的 feed 都能正常抓取及顯示。

**Comment by lchanc3** [comment]
原來 Feedbro 無法讀取新文章跟時區有關，感謝你的測試！

我的Feed Reader 是 n8n 的 [RssFeedReadTrigger](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/RssFeedRead/RssFeedReadTrigger.node.ts)，在執行時，它會遍歷整個 Feed。如果 Feed 的順序是反的，它就會把第一筆資料（理應是最新的一筆，卻是最舊的資料）視為上一次檢查的內容。因此，它會一直認為有新 Feed 的問題，不過這只是我的推測，因為我對 TypeScript不熟
如果在批踢踢的路由後面加上查詢的語法，就會因為批踢踢網頁版的排序方式不一樣而變正常。

本來是想用 n8n 串接其他服務作為閱讀器使用，後來發現這樣下來自己不會想好好看文章，所以最近在物色新的閱讀器，最近我也來研究一下 ttrss 好了

**Comment by cldotdev** [comment]
已修正以下問題，應該可以解決上述問題了。

1. 遊戲角落：修正來源連結失效
2. PTT：
    (1) 在 updated 加上時區，測試 Feedbro 可正常抓取
    (2) feed 排序固定改為最新在前
